### ISSUE TITLE
skelenox config issues

### ISSUE THREAD

**Issue by Enchantertim** [ANSSI-FR/polichombr#92]
When trying to use skelenox with Ida Pro 6.95 on the mac, there are a few issues:
**1: Port number**
Port number as defined in skelsettings.json yields a unicode string. on the mac this triggers a bug:
```
[11/03/2017 10:26] [ERROR] [MainThread]: The polichombr server seems down
Traceback (most recent call last):
File "/scripts/skelenox/skelenox.py", line 148, in get_online
self.__do_init()
File "/scripts/skelenox/skelenox.py", line 164, in __do_init
self.h_conn.connect()
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in connect
self.timeout, self.source_address)
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
for res in getaddrinfo(host, port, 0, SOCK_STREAM):
error: getaddrinfo() argument 2 must be integer or string
```
Solution is to  use  "poli_port": 5000, instead of     "poli_port": "5000",

**2: communication with polichombr**
when loading the script in ida, the following occurs:
```
[12/03/2017 05:55] [ERROR] [MainThread]: HTTPS is not managed at the moment...
[12/03/2017 05:55] [INFO] [MainThread]: Skelenox init finished
[12/03/2017 05:55] [ERROR] [SkelSyncAgent]: The GET request didn't go as expected
[12/03/2017 05:55] [ERROR] [SkelSyncAgent]: 
Traceback (most recent call last):
  File "/scripts/skelenox/skelenox.py", line 892, in run
    self.sync_names()
  File "/scripts/skelenox/skelenox.py", line 833, in sync_names
    comments = self.skel_conn.get_comments(timestamp=self.last_timestamp)
  File "/scripts/skelenox/skelenox.py", line 329, in get_comments
    res = self.poli_get(endpoint)
  File "/scripts/skelenox/skelenox.py", line 216, in poli_get
    result = self.poli_request(endpoint, data, method='GET')
  File "/scripts/skelenox/skelenox.py", line 208, in poli_request
    raise IOError
IOError
```
On the server side of things, with debugging turned on, the following is logged:
```
ERROR in webui [/web/polichombr/poli/views/webui.py:58]:
404 Not Found: The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.
--------------------------------------------------------------------------------
192.168.2.55 - - [11/Mar/2017 17:37:38] "GET /2/comments/?timestamp=1970-01-01T01:00:00.000000 HTTP/1.1" 404 -

```
I haven't been able to track this down yet.

**Comment by harfangeek** [comment]
**1: port number in skelenox.json**

It's strange, personnally when I download the skelenox script the port number is written as a number, not as a string.

**2: communication with polichombr**

I encountered the same bug. The problem is that the request is made to 
`/2/comments/?timestamp=1970-01-01T01:00:00.000000`
but it should be made to 
`/api/1.0/samples/2/comments/?timestamp=1970-01-01T01:00:00.000000`

A quick dirty correction is to set the 'poli_remote_path' option in skelonx.json to "/api/1.0/samples/" and it should now work. I'm not sure if this bug comes from the skelenox.py script or from the server side who doesn't redirect the REST API to the right endpoint. I try to make a pull request soon when I have a better correction.

**Comment by Enchantertim** [comment]
For #1: No idea whats causing it then. The machine where polichombr is running is a stock ubuntu 16 vm. Nothing too strange there (although I had an issue with not setting UTF-8 as a locale there when running the application)
As for #2: This fixes the problem. If poli_remote_path is not used for anything else, it could be fixed during the creation of the skelsettings.json. 

Now to figure out why I randomly get the confused psyduck when looking for a disassemble for functions :P

**Comment by tpo-anssi** [comment]
The problem with the port is caused by the function ```dl_skelenox``` in the [webui.py](https://github.com/ANSSI-FR/polichombr/blob/master/poli/views/webui.py#L167).
If you run the default server (eg ```python run.py```), the port will be the default 5000 and defined as a string. However, if you run Polichombr using ```uwsgi``` then it is defaulted to 80 as a number.

Concerning the API path, the problem is known (see PR #81 ), and a quick fix is effectively to set it in the configuration. It should be defined as a config parameter instead of a dirty string in ```__init__.py```

A patch fixing those bugs will be pushed in the following weeks

**Comment by tpo-anssi** [comment]
Renamed since the bug does not depends on Mac

**Comment by tpo-anssi** [comment]
Could you test with commit 08c1dfa0ea4d6f783a452777fca64e65ec0b4c11 ?
It should fix both the port bug
and the ```/api/1.0/samples``` endpoint bug

**Comment by Enchantertim** [comment]
Both are fixed with this commit. 👍
